version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  frontend:
    build:
      context: .
    command: streamlit run streamlit_client.py
    ports:
      - "8501:8501"
    depends_on:
      - backend
