FROM python:3.10

WORKDIR /app

COPY requirements_backend.txt .
RUN pip install --no-cache-dir -r requirements_backend.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "mcp_servers.employee_mcp_server:app", "--host", "0.0.0.0", "--port", "8000"]
